[tool.pylint.messages_control]
disable = [
    "missing-function-docstring",
    "missing-class-docstring",
    "C0103",
    "C0301",
    "E0401",
    "E0611",
    "R0914",
    "R0915",
    "C0114",
    "E1129",
    "R0801"
]

[tool.black]
line-length = 88